# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196ed0290ecf87e442be321796c593ab1bdcd66777d620b95ac830f3900b5770df0a42fb83571f18ac1b7aa72bd10ee3c3413c7bcfc868d9c0422356725ff0df

test:
  secret_key_base: 55eb3682ebbd357c04bb3feae0af5b5bfd2b810c1f05f5fbfa7d4e3f0638722fc771ce5945e1ff370a69a24c0a3c0994da7846178508aabb59780bf9decfa5de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
